version: '3.3'
services:
  backend:
    container_name: payment_gateway_api
    build: src
    environment:
      BankApi__Port: "12345"
      ASPNETCORE_ENVIRONMENT: "Development",
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=db; user=user; password=password; Persist Security Info=False; Connect Timeout=300"
    ports:
      - "5001:80"
    depends_on:
      - "db"
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: